### ISSUE TITLE
Improve documentation for building new consumers.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-redis-consumer#114]

**Comment by ngreenwald** [comment]
Some things that would be helpful:
- An ordered, step-by-step list of tasks to accomplish in order to create a custom consumer. Right now it's more of a narrative flow, which makes it hard to figure out where to get started.

- Docstrings for the functions inside of ImageConsumer, to help understand what is going on. 

-  Given that people will likely use ImageConsumer as a guide, giving more specifics on what is defined within the consumer, what is defined in settings (such as permitted pre- and post-processing functions) would be helpful.

**Comment by willgraf** [comment]
Closed by #120
